### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkPizza** [cyberofficial/TTVDropBot#19]
`Something went wrong...
Login failed for an unknown reason...
The Reason is probably:
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'error_code' of undefined
      at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:221:95
      at Generator.next (<anonymous>)
      at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:8:71
      at new Promise (<anonymous>)
      at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:4:12
      at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:154:20
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    [stack]: "TypeError: Cannot read property 'error_code' of undefined\n" +
      '    at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:221:95\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:8:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:4:12\n' +
      '    at /snapshot/TTVDropBot/build/functions/login/defaultlogin.js:154:20\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
    [message]: "Cannot read property 'error_code' of undefined"
  }
}
Unhandled Rejection Reason: TypeError: Cannot read property 'error_code' of undefined`

I am trying to use the `Directly option via Command Line` to login.

**Comment by DarkPizza** [comment]
I forgot to mention, I am using ubuntu-20.04-x86_64.
