### ISSUE TITLE
Unhandled Rejection at: Promise {

### ISSUE THREAD

**Issue by Zerolight** [cyberofficial/TTVDropBot#4]
Running on Heroku sometimes still getting GQL response error, is there a env variable for those running on heroku?
And sometimes get the following error randomly crashing it

`022-11-03T16:20:39.174135+00:00 app[worker.1]: Current Progress: 0 % | Watched 0/240 Minutes | Drop 7/7 | Status Active | isClaimed false

2022-11-03T16:20:39.174274+00:00 app[worker.1]:  

2022-11-03T16:20:39.176831+00:00 app[worker.1]: Skipping extra channel points, disabled in settings.

2022-11-03T16:23:47.367319+00:00 heroku[worker.1]: Process exited with status 21

2022-11-03T16:23:47.431521+00:00 heroku[worker.1]: State changed from up to crashed

2022-11-03T16:23:47.221140+00:00 app[worker.1]: Unhandled Rejection at: Promise {

2022-11-03T16:23:47.221167+00:00 app[worker.1]:   <rejected> FetchError: request to https://twitch.tv/ failed, reason: connect ETIMEDOUT 151.101.66.167:443

2022-11-03T16:23:47.221170+00:00 app[worker.1]:       at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)

2022-11-03T16:23:47.221171+00:00 app[worker.1]:       at ClientRequest.emit (node:events:513:28)

2022-11-03T16:23:47.221172+00:00 app[worker.1]:       at TLSSocket.socketErrorListener (node:_http_client:494:9)

2022-11-03T16:23:47.221172+00:00 app[worker.1]:       at TLSSocket.emit (node:events:513:28)

2022-11-03T16:23:47.221172+00:00 app[worker.1]:       at emitErrorNT (node:internal/streams/destroy:157:8)

2022-11-03T16:23:47.221172+00:00 app[worker.1]:       at emitErrorCloseNT (node:internal/streams/destroy:122:3)

2022-11-03T16:23:47.221173+00:00 app[worker.1]:       at processTicksAndRejections (node:internal/process/task_queues:83:21) {

2022-11-03T16:23:47.221173+00:00 app[worker.1]:     message: 'request to https://twitch.tv/ failed, reason: connect ETIMEDOUT 151.101.66.167:443',

2022-11-03T16:23:47.221174+00:00 app[worker.1]:     type: 'system',

2022-11-03T16:23:47.221174+00:00 app[worker.1]:     errno: 'ETIMEDOUT',

2022-11-03T16:23:47.221175+00:00 app[worker.1]:     code: 'ETIMEDOUT',

2022-11-03T16:23:47.221175+00:00 app[worker.1]:     [stack]: 'FetchError: request to https://twitch.tv/ failed, reason: connect ETIMEDOUT 151.101.66.167:443\n' +

2022-11-03T16:23:47.221176+00:00 app[worker.1]:       '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)\n' +

2022-11-03T16:23:47.221176+00:00 app[worker.1]:       '    at ClientRequest.emit (node:events:513:28)\n' +

2022-11-03T16:23:47.221176+00:00 app[worker.1]:       '    at TLSSocket.socketErrorListener (node:_http_client:494:9)\n' +

2022-11-03T16:23:47.221176+00:00 app[worker.1]:       '    at TLSSocket.emit (node:events:513:28)\n' +

2022-11-03T16:23:47.221177+00:00 app[worker.1]:       '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +

2022-11-03T16:23:47.221177+00:00 app[worker.1]:       '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +

2022-11-03T16:23:47.221177+00:00 app[worker.1]:       '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',

2022-11-03T16:23:47.221177+00:00 app[worker.1]:     name: 'FetchError'

2022-11-03T16:23:47.221178+00:00 app[worker.1]:   }

2022-11-03T16:23:47.221178+00:00 app[worker.1]: }

2022-11-03T16:23:47.221351+00:00 app[worker.1]: Unhandled Rejection Reason: FetchError: request to https://twitch.tv/ failed, reason: connect ETIMEDOUT 151.101.66.167:443`

**Comment by cyberofficial** [comment]
I'm not familiar with heroku, is it a linux operating system?

**Comment by Zerolight** [comment]
Heroku is a container-based cloud Platform as a Service.

Similar or is using the docker implementation, instead of settings it uses Environment variables as seen in documentation.
ttvdropbot_ variables on start, I think the unhandled rejection might just be network issue at the time but uncertain.

**Comment by cyberofficial** [comment]
I believe it might be a net work issue, after looking at your error in full.
I can see If i can better handle those errors and prevent crashing upon net work error. Might just add a simple error handling method.

**Comment by cyberofficial** [comment]
Hello, sorry for the delayed reply, check out my post #10 , will be doing a major revision of this bot and code.
