### ISSUE TITLE
Getting ETIMEOUT error running on Ubuntu

### ISSUE THREAD

**Issue by ShirowLeBG** [cyberofficial/TTVDropBot#6]
Hi, I sometime get this error while running the bot after 2/3 hours, any fix or solution you can think ?

```
2022-11-14 08:37:38: Unhandled Rejection at: Promise {
  <rejected> FetchError: request to https://www.twitch.tv/ failed, reason: connect ETIMEDOUT 199.232.138.167:443
      at ClientRequest.<anonymous> (/snapshot/TTVDropBot/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (events.js:400:28)
      at TLSSocket.socketErrorListener (_http_client.js:475:9)
      at TLSSocket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    message: 'request to https://www.twitch.tv/ failed, reason: connect ETIMEDOUT 199.232.138.167:443',
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    [stack]: 'FetchError: request to https://www.twitch.tv/ failed, reason: connect ETIMEDOUT 199.232.138.167:443\n' +
      '    at ClientRequest.<anonymous> (/snapshot/TTVDropBot/node_modules/node-fetch/lib/index.js:1491:11)\n' +
      '    at ClientRequest.emit (events.js:400:28)\n' +
      '    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n' +
      '    at TLSSocket.emit (events.js:400:28)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
    name: 'FetchError'
  }
}
2022-11-14 08:37:38: Unhandled Rejection Reason: FetchError: request to https://www.twitch.tv/ failed, reason: connect ETIMEDOUT 199.232.138.167:443
```

**Comment by cyberofficial** [comment]
This errors means the twitch.com is basically spitting errors itself. It's not the program, it is the website, usually fixes by it self.

Also please cout out #10 Important Info, I will updating this repo fairly soon. Sorry for the late reply 🙇
